import os

DOS = input("Dosya yolu: ")
print("---------------------------------")
print("--onefile        → tek .exe dosyası")
print("--onedir         → klasör halinde (varsayılan)")
print("--noconsole      → konsol penceresi açılmaz (GUI için)")
print("--windowed       → --noconsole ile aynı")
print("--icon=icon.ico  → .exe ikonunu ayarlar")
print("--name=isim      → çıktı dosyasının adını ayarlar")
print("--add-data       → ekstra dosya/klasör ekler")
print("--hidden-import  → otomatik algılanamayan modülleri ekler")
print("--clean          → build öncesi cache temizler")
print("--debug          → debug modu")
print("--upx-dir        → UPX ile sıkıştırma (boyut küçültür)")
print("--version-file   → .exe versiyon bilgisi ekler")
EKS = input("Kullanmak istediğiniz parametreyi girin: ")
os.system(f"pyinstaller {EKS} {DOS}")
print("[EXE YAPICI] yapma bitti")
input("Çıkmak İçin ENTER e basın")